### ISSUE TITLE
Entities invisible/Error

### ISSUE THREAD

**Issue by ghost** [VisiVersa/Manic#1]
https://mclo.gs/pJeJk5X
Mobs from manic appear as invisible aside from the error texture replacing the head region

**Comment by Nycleo** [comment]
Still an issue on the 1.20.1 version.
Is there any way to fix this? :')
Idk if its because of the same problem than here...

**Comment by ward-hop** [comment]
Same issue here, on 1.20.1.
Also applies to mobs from Sanguine.
Entities are invisible, with models apparently replaced by other textures, in my case potions.

**Comment by ShokCat** [comment]
I've found out that this issue is caused by sodium for some reason, not sure if that'll help or not.

**Comment by tiigerbones** [comment]
Def need a fix still on 1.20.1
both mods have this issue going below sodium 5.0 would really suck

**Comment by VisiVersa** [comment]
Please read the FAQ, sorry for a year's late response but I hope you figured it out by now
Also the sodium issue is fixed in next (unreleased) version according to beta tests
